# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0
import py_backwards.exceptions as module_1


def test_case_0():
    list_0 = []
    none_type_0 = module_0.debug(list_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    str_0 = '"MC'
    callable_0 = module_0.eager(str_0)


def test_case_3():
    none_type_0 = None
    module_0.get_source(none_type_0)


def test_case_4():
    none_type_0 = None
    none_type_1 = module_0.warn(none_type_0)


def test_case_5():
    none_type_0 = None
    transformation_error_0 = module_1.TransformationError(
        none_type_0, none_type_0, none_type_0, none_type_0
    )
    variables_generator_0 = module_0.VariablesGenerator()
    none_type_1 = module_0.debug(variables_generator_0)
    none_type_2 = module_0.warn(none_type_0)
    callable_0 = module_0.eager(none_type_2)
    callable_0.__call__(
        variables_generator_0, callable_0, qualname=transformation_error_0
    )
